services:
  postgres:
    ports:
      - "5432:5432"

  postgres_replica:
    ports:
      - "5433:5432"

  localstack:
    ports:
      - "4566:4566"

  auth:
    ports:
      - "8090:8080"

  api:
    ports:
      - "8080:8080"
